
title: Project Page
description: > # this means to ignore newlines until "baseurl:"
  Data Science project and blog page.
permalink: ':title/'
baseurl: "/projects"
url: "http://porphyrin.github.io"

# Author Settings
author: Olivia Warren
author-img: ow_headshot.jpg
about-author: Data Scientist. Python enthusiast. Biotech nerd. Ex-Management Consultant.
github: porphyrin
linkedin: olivia-warren

# Tracker
# analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
